name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'docs/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            nathanzk/simple-mq:${{ steps.sha.outputs.short }}
            ${{ github.ref == 'refs/heads/main' && 'nathanzk/simple-mq:latest' || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  terraform:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/912075731847/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: terraform@simple-mq.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Deploy to VM
        run: |
            gcloud compute ssh appuser@simple-mq-vm --zone=${{ vars.GCP_ZONE }} --command="
              cd /opt/simple-mq &&
              git config --global --add safe.directory /opt/simple-mq
              git pull &&
              echo 'OTLP_ENDPOINT=${{ secrets.OTLP_ENDPOINT }}' > .env &&
              echo 'OTLP_AUTH=${{ secrets.OTLP_AUTH }}' >> .env &&
              docker pull nathanzk/simple-mq:latest &&
              docker-compose up -d
            "